apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: v28.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://traefik.github.io/charts
