apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "6.24.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    provider: cloudflare
    cloudflare:
      secretName: external-dns-cf-token
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: kube-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts
