apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: post-api
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/toledompm/post-api.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: post-api
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: post-api
